-- ============================
-- ENTIDADES BÁSICAS
-- ============================

CREATE TABLE CENTRO_EDUCATIVO (
id INT AUTO_INCREMENT PRIMARY KEY,
nombreCentro VARCHAR(255) NOT NULL UNIQUE,
sufijoEmail VARCHAR(255)
);

CREATE TABLE TITULO (
id INT AUTO_INCREMENT PRIMARY KEY,
nombreTitulo VARCHAR(255) NOT NULL
);

CREATE TABLE CURSO (
id INT AUTO_INCREMENT PRIMARY KEY,
numCurso CHAR(1) NOT NULL
);

CREATE TABLE MODULO (
id INT AUTO_INCREMENT PRIMARY KEY,
nombreModulo VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE ROL (
id INT AUTO_INCREMENT PRIMARY KEY,
nombreGrupo VARCHAR(255) NOT NULL,
permisos TEXT
);

CREATE TABLE USUARIO (
tokken VARCHAR(255) PRIMARY KEY,
userName VARCHAR(255) NOT NULL UNIQUE,
passwrd VARCHAR(255) NOT NULL,
email VARCHAR(255) NOT NULL UNIQUE,
fecCreacion DATETIME
);

CREATE TABLE PROYECTO (
id INT AUTO_INCREMENT PRIMARY KEY,
nombreProyecto VARCHAR(255) NOT NULL,
descripcionProyecto TEXT,
urlProyecto VARCHAR(255),
urlGitHub VARCHAR(255),
imgPortada VARCHAR(255)
);

-- ============================
-- TABLAS INTERMEDIAS N:M
-- ============================

-- 1) ROL <-> USUARIO
CREATE TABLE ROL_USUARIO (
rolId INT NOT NULL,
tokken VARCHAR(255) NOT NULL,
PRIMARY KEY (rolId, tokken),
FOREIGN KEY (rolId) REFERENCES ROL(id),
FOREIGN KEY (tokken) REFERENCES USUARIO(tokken)
);

-- 2) USUARIO <-> PROYECTO
CREATE TABLE USUARIO_PROYECTO (
tokken VARCHAR(255) NOT NULL,
proyectoId INT NOT NULL,
PRIMARY KEY (tokken, proyectoId),
FOREIGN KEY (tokken) REFERENCES USUARIO(tokken),
FOREIGN KEY (proyectoId) REFERENCES PROYECTO(id)
);

-- 3) PROYECTO <-> CENTRO_EDUCATIVO
CREATE TABLE PROYECTO_CENTRO (
proyectoId INT NOT NULL,
centroId INT NOT NULL,
PRIMARY KEY (proyectoId, centroId),
FOREIGN KEY (proyectoId) REFERENCES PROYECTO(id),
FOREIGN KEY (centroId) REFERENCES CENTRO_EDUCATIVO(id)
);

-- 4) CENTRO_EDUCATIVO <-> TITULO
CREATE TABLE CENTRO_TITULO (
centroId INT NOT NULL,
tituloId INT NOT NULL,
PRIMARY KEY (centroId, tituloId),
FOREIGN KEY (centroId) REFERENCES CENTRO_EDUCATIVO(id),
FOREIGN KEY (tituloId) REFERENCES TITULO(id)
);

-- 5) TITULO <-> CURSO
CREATE TABLE TITULO_CURSO (
tituloId INT NOT NULL,
cursoId INT NOT NULL,
PRIMARY KEY (tituloId, cursoId),
FOREIGN KEY (tituloId) REFERENCES TITULO(id),
FOREIGN KEY (cursoId) REFERENCES CURSO(id)
);

-- 6) CURSO <-> MODULO
CREATE TABLE CURSO_MODULO (
cursoId INT NOT NULL,
moduloId INT NOT NULL,
PRIMARY KEY (cursoId, moduloId),
FOREIGN KEY (cursoId) REFERENCES CURSO(id),
FOREIGN KEY (moduloId) REFERENCES MODULO(id)
);
